version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: counter-redis
    command: redis-server --requirepass root123123 --user root on >root123123 ~* +@all
    ports:
      - '6379:6379'
    environment:
      - REDIS_USERNAME=root
      - REDIS_PASSWORD=root123123
    volumes:
      - redis_data:/data

  mongodb:
    image: mongo:latest
    container_name: counter-mongodb
    command: mongod --bind_ip_all
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123123

volumes:
  redis_data:
  mongodb_data:
