version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: counter-redis
    command: redis-server --requirepass   adminpassword
    ports:
      - '6379:6379'
    environment:
      - REDIS_USERNAME=admin
      - REDIS_PASSWORD=adminpassword
    volumes:
      - redis_data:/data

  mongodb:
    image: mongo:latest
    container_name: counter-mongodb
    command: mongod --bind_ip_all
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword

volumes:
  redis_data:
  mongodb_data:
