version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: counter-redis
    environment:
      - REDIS_USERNAME=root
      - REDIS_PASSWORD=root123123
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    network_mode: 'host'

  mongodb:
    image: mongo:latest
    container_name: counter-mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123123
    network_mode: 'host'

volumes:
  redis_data:
  mongodb_data:
